server:
  port: 10100

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:com/cheche/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.cheche.entity
  type-enums-package: com.cheche.entity.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql

spring:
  profiles:
    active: vertical-database
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/study?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
